Try building pages for each branch

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,11 +5,11 @@ variables:
     CARGO_HOME: $CI_PROJECT_DIR/cargo
     FF_ENABLE_BASH_EXIT_CODE_CHECK: "true"
     GIT_SUBMODULE_STRATEGY: normal
+    EPHEMERAL_BRANCHES_PATH: preview # subpath where previews of pages will be built
 
 stages:
     - test
     - build
-    - pages
 
 clippy:
     stage: test
@@ -31,6 +31,8 @@ clippy:
         paths:
             - target
             - $CARGO_HOME
+    rules:
+        - when: always
 
 test:
     stage: test
@@ -43,6 +45,8 @@ test:
         paths:
             - target
             - $CARGO_HOME
+    rules:
+        - when: always
 
 
 cargo-fmt:
@@ -52,6 +56,8 @@ cargo-fmt:
     script:
         # pass --check to rustfmt to error if un-formatted
         - cargo fmt -- --check
+    rules:
+        - when: always
 
 typos-and-todos:
     stage: test
@@ -76,6 +82,8 @@ typos-and-todos:
               ./typos src || echo ""
               set -e; find src -name "*.rs" | xargs grep -Ei "// *TODO" || echo ""
             fi
+    rules:
+        - when: always
 
 linux_build:
     stage: build
@@ -95,15 +103,29 @@ linux_build:
         paths:
             - target
             - $CARGO_HOME
+    rules:
+        - if: $CI_COMMIT_BRANCH == "main"
+          when: always
+        - when: never
 
+# Modified from https://dev.to/zenika/gitlab-pages-preview-the-no-compromise-hack-to-serve-per-branch-pages-5599
+# in order to get preview pages for WIP branches
 pages:
+    # Perhaps this makes more sense in the build, but doing it in parallel should give
+    # us a gitlab pages-thing quicker
+    stage: test
     cache:
-        key:
-            files:
-                - Cargo.lock
-        paths:
-            - target
-            - $CARGO_HOME
+        key: gitlab-pages
+        paths: [public]
+    before_script:
+        # CURRENT_CONTENT_PATH is defined in rules, different between main branch and ephemeral branches
+        - mkdir -p public/$CURRENT_CONTENT_PATH && ls public/$CURRENT_CONTENT_PATH/..
+        - | # avoid deleting main branch content when cache has been erased
+          if [ "$CI_COMMIT_BRANCH" != "$CI_DEFAULT_BRANCH" ] && [ ! -d public/$CI_DEFAULT_BRANCH ]; then
+            echo -e "💥\e[91;1m Unable to retrieve $CI_DEFAULT_BRANCH generated files from cache ; please regenerate $CI_DEFAULT_BRANCH files first\e[0m"
+            exit 1
+          fi
+        - rm -rf public/$CURRENT_CONTENT_PATH || true # remove last version of current branch
     script:
         - rustup target add wasm32-unknown-unknown
         - wget -qO- https://github.com/thedodd/trunk/releases/download/v0.17.5/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
@@ -114,10 +136,22 @@ pages:
           # to download our artefacts and put them wherever on their webserver. To fix this,
           # wel'll build with a dummy public URL, then replace it with ./
         - ./trunk build --release --public-url /dist
-        - cp -r dist public
+        - cp -r dist public/$CURRENT_CONTENT_PATH
           # We have to do this from the source file instead of public/ because sed
           # does not replace in place
-        - sed -e "s|/dist/|./|g" dist/index.html > public/index.html
+        - sed -e "s|/dist/|./|g" dist/index.html > public/$CURRENT_CONTENT_PATH/index.html
+        - echo "PreviewUrl surfer-project.org/$CURRENT_CONTENT_PATH/index.html" > metrics.txt
+    rules:
+        # 'main branch' is exposed at GitLab Pages root
+        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+          variables:
+            CURRENT_CONTENT_PATH: "."
+        # other (short-lived) branches generation are exposed in 'EPHEMERAL_BRANCHES_PATH/branch-name-sanitized' sub path
+        - variables:
+            CURRENT_CONTENT_PATH: $EPHEMERAL_BRANCHES_PATH/$CI_COMMIT_REF_SLUG
     artifacts:
         paths:
             - public
+        reports:
+            metrics: metrics.txt
+        expire_in: 1h
